apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend-deployment
  labels:
    app: chat-frontend-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      volumes:
      - name: nginx-configmap-volume
        configMap:
          name: nginx-configmap 
      containers:
      - name: chat-frontend
        image: josedoporto/chat-frontend
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: nginx-configmap-volume
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: chat-frontend-service
spec:
  selector:
    app: chat-frontend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000