apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-micro-deployment
  labels:
    microservice: auth
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: auth-micro
  template:
    metadata:
      labels:
        app: auth-micro
    spec:
      containers:
      - name: chat-auth
        image: josedoporto/chat-auth
        ports:
        - containerPort: 5000
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: chat-app-secret
              key: mongo-root-username 
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: chat-app-secret
              key: mongo-root-password
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: chat-app-secret
              key: jwt-secret
        - name: CREDENTIALS_URL
          value: "mongodb:/$(ME_CONFIG_MONGODB_ADMINUSERNAME):$(ME_CONFIG_MONGODB_ADMINPASSWORD)@auth-db-service:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-micro-service
spec:
  selector:
    app: auth-micro
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000